### ISSUE TITLE
Api broken

### ISSUE THREAD

**Issue by ClancyS5** [danadum/empire-api#2]
Api is broken, cant search by name, nobility contest doesnt work and shapeshifters doesnt too, the rest works fine

**Comment by danadum** [comment]
- The search by name has been fixed, it should work now. It's still not working on a few rankings, the ones that aren't accessible in game (nomads, black wheel...) but this is an issue from GGE side so it can't be solved.
- Most of the nobility contests are working, only a few are broken. Again, this is an issue from GGE side so it can't be solved.
- Shapeshifters works fine.
